site_name: latz
repo_url: https://github.com/travishathaway/latz
repo_name: travishathaway/latz

theme:
  name: material
  palette:
    primary: blue-grey
  features:
    - content.code.annotate

markdown_extensions:
  - mkdocs-click
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: "!!python/name:materialx.emoji.twemoji"
      emoji_generator: "!!python/name:materialx.emoji.to_svg"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [./]
