from typing import Any

class ConfigValuesValidator:
    def __init__(self) -> None: ...
    def __call__(self, ctx, _, values) -> dict[str, str]: ...
    def validate_single_value(self, value: str) -> dict: ...

def get_dotted_path_value(nest: dict, dotted_path: str) -> Any: ...
def get_nested_dict_from_path(path: str, value: Any) -> dict: ...
